[tool.poetry]
name = "aoc2023"
version = "0.1.0"
description = ""
authors = ["Michal Cech"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
